name: Deploy Demo to Cloudflare Pages

on:
  push:
    branches:
      - main
    paths:
      - 'packages/demo/**'
      - 'packages/vyuh_node_flow/lib/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get workspace dependencies
        run: dart pub get

      - name: Bootstrap workspace with Melos
        run: dart run melos bootstrap

      - name: Build Flutter web app
        run: |
          cd packages/demo
          flutter build web --release --wasm

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy packages/demo/build/web --project-name=vyuh-node-flow
