name: Publish to pub.dev

on:
  push:
    branches:
      - main
    paths:
      - 'packages/vyuh_node_flow/**'
      - '.github/**'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Melos
        run: dart pub global activate melos

      - name: Setup pub credentials
        run: |
          mkdir -p $HOME/.pub-cache
          cat <<EOF > $HOME/.pub-cache/credentials.json
          ${{ secrets.PUB_DEV_CREDENTIALS }}
          EOF

      - name: Get workspace dependencies
        run: dart pub get

      - name: Bootstrap workspace with Melos
        run: dart run melos bootstrap

      - name: Analyze code
        run: dart run melos run analyze

      - name: Publish to pub.dev
        env:
          PUB_CACHE: $HOME/.pub-cache
        run: |
          cd packages/vyuh_node_flow
          dart pub publish --force
