name: Publish to pub.dev

on:
  push:
    branches:
      - main
    paths:
      - 'packages/vyuh_node_flow/**'
      - '.github/**'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get workspace dependencies
        run: dart pub get

      - name: Install Melos
        run: dart pub global activate melos

      - name: Bootstrap workspace with Melos
        run: melos bootstrap

      - name: Analyze code
        run: melos run analyze

      - name: Publish to pub.dev
        uses: k-paxian/dart-package-publisher@v1.6
        with:
          credentialJson: ${{ secrets.PUB_DEV_CREDENTIALS }}
          flutter: true
          skipTests: true
          relativePath: packages/vyuh_node_flow
