name: Publish to pub.dev

on:
  push:
    branches:
      - main
    paths:
      - 'lib/**'
      - 'assets/**'
      - '.github/**'
      - 'pubspec.yaml'
      - 'CHANGELOG.md'
      - 'README.md'
      - 'LICENSE'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze code
        run: dart analyze

      - name: Publish to pub.dev
        uses: k-paxian/dart-package-publisher@v1.6
        with:
          credentialJson: ${{ secrets.PUB_DEV_CREDENTIALS }}
          flutter: true
          skipTests: true
